export const SET_PRODUCTS = "set_products"
export const SET_SINGLE_PRODUCT = "set_single_product"
export const SET_FILTERED_PRODUCTS = "set_filtered_products"
export const SET_BOOKMARKS = "set_bookmarks"
export const SET_ADD_TO_CART = "set_add_to_cart"
export const SET_PRODUCTS_CART = "set_products_cart"
